export {
  ubicaciones,
  ubicacionSearch,
  ubicacionPorId,
  misUbicaciones,
  misUbicacionesHistorial,
  misUbicacionesGuardadas,
  ubicacionesPorIdUsuarioPorHistorial,
  ubicacionesGuardadas,
  ubicacionesHistorial,
  ubicacionesPorIdEntrega,
  ubicacionesLatLonCent,
  ubicacionesLatLonDec,
  ubicacionesLatLonCentGuardadas,
  ubicacionesLatLonCentHistorial,
  ubicacionesLatLonDecGuardadas,
  ubicacionesLatLonDecHistorial,
  registrarUbicacion,
  registrarAdmonOrigenDestinoDefault,
  editarUbicacion,
  editarUbicacionFrm,
  eliminarUbicacion,
} from './api.js';
export type { Ubicacion } from './types.js';
