export {
  entregaPlantillaTodas,
  entregaPlantillaSearch,
  entregaPlantillaSearchIdCliente,
  entregaPlantillaQId,
  entregaPlantillaQIdCliente,
  entregaPlantillaQMias,
  entregaPlantillaQIdClienteCodigoGrupo,
  entregaPlantillaQCodigoGrupoAdmon,
  entregaPlantillaQIdClienteCodigoGrupoAdmon,
  entregaPlantillaQIdEntrega,
  entregaPlantillaQIdPaquete,
  entregaPlantillaQIdSeguro,
  entregaPlantillaQIdTipoPago,
  entregaPlantillaQIdTarjeta,
  entregaPlantillaQEnviarRecibir,
  entregaPlantillaQDefault,
  entregaPlantillaQLatLonOrigen,
  entregaPlantillaQLatLonDestino,
  entregaPlantillaQContactoTelefonoCodigoPaisOrigen,
  entregaPlantillaQContactoTelefonoOrigen,
  entregaPlantillaQContactoTelefonoCodigoPaisDestino,
  entregaPlantillaQContactoTelefonoDestino,
  registrarPlantilla,
  editarPlantilla,
  eliminarPlantilla,
} from './api.js';
export type { EntregaPlantilla } from './types.js';
