import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'react/index': 'src/react/index.ts',
    'modules/sesion/index': 'src/modules/sesion/index.ts',
    'modules/usuario/index': 'src/modules/usuario/index.ts',
    'modules/entrega/index': 'src/modules/entrega/index.ts',
    'modules/negocio/index': 'src/modules/negocio/index.ts',
    'modules/cliente/index': 'src/modules/cliente/index.ts',
    'modules/ubicacion/index': 'src/modules/ubicacion/index.ts',
    'modules/orden/index': 'src/modules/orden/index.ts',
    'modules/producto/index': 'src/modules/producto/index.ts',
    'modules/saldo_usuario/index': 'src/modules/saldo_usuario/index.ts',
    'modules/notificacion/index': 'src/modules/notificacion/index.ts',
    'modules/rol/index': 'src/modules/rol/index.ts',
    'modules/informacion_basica/index': 'src/modules/informacion_basica/index.ts',
    'modules/categoria/index': 'src/modules/categoria/index.ts',
    'modules/negocio_cliente/index': 'src/modules/negocio_cliente/index.ts',
    'modules/link_pago/index': 'src/modules/link_pago/index.ts',
    'modules/concepto/index': 'src/modules/concepto/index.ts',
    'modules/entrega_gps/index': 'src/modules/entrega_gps/index.ts',
    'modules/entrega_evidencia/index': 'src/modules/entrega_evidencia/index.ts',
    'modules/entrega_mensaje/index': 'src/modules/entrega_mensaje/index.ts',
    'modules/entrega_repartidor/index': 'src/modules/entrega_repartidor/index.ts',
    'modules/entrega_usuario_calificacion/index': 'src/modules/entrega_usuario_calificacion/index.ts',
    'modules/entrega_plantilla/index': 'src/modules/entrega_plantilla/index.ts',
    'modules/entrega_multa_aborcion/index': 'src/modules/entrega_multa_aborcion/index.ts',
    'modules/entrega_multa_cancelacion/index': 'src/modules/entrega_multa_cancelacion/index.ts',
    'modules/estatus_entrega/index': 'src/modules/estatus_entrega/index.ts',
    'modules/pago/index': 'src/modules/pago/index.ts',
    'modules/movimiento/index': 'src/modules/movimiento/index.ts',
    'modules/deposito/index': 'src/modules/deposito/index.ts',
    'modules/retiro/index': 'src/modules/retiro/index.ts',
    'modules/abono/index': 'src/modules/abono/index.ts',
    'modules/adeudo/index': 'src/modules/adeudo/index.ts',
    'modules/estatus_pago/index': 'src/modules/estatus_pago/index.ts',
    'modules/tipo_pago/index': 'src/modules/tipo_pago/index.ts',
    'modules/repartidor_on/index': 'src/modules/repartidor_on/index.ts',
    'modules/jornada/index': 'src/modules/jornada/index.ts',
    'modules/uccc/index': 'src/modules/uccc/index.ts',
    'modules/uve/index': 'src/modules/uve/index.ts',
    'modules/uvt/index': 'src/modules/uvt/index.ts',
    // ── Adjuntos ─────────────────────────────────────────────────────────────
    'modules/tipo_adjunto/index':      'src/modules/tipo_adjunto/index.ts',
    'modules/adjunto/index':           'src/modules/adjunto/index.ts',
    'modules/adjunto_referencia/index':'src/modules/adjunto_referencia/index.ts',
    // ── Entregas (extra) ──────────────────────────────────────────────────────
    'modules/entrega_estatus/index':   'src/modules/entrega_estatus/index.ts',
    // ── Notificaciones (extra) ────────────────────────────────────────────────
    'modules/tipo_notificacion/index': 'src/modules/tipo_notificacion/index.ts',
    // ── Stub modules (store-only; no client API yet) ──────────────────────────
    'modules/producto_variante/index':        'src/modules/producto_variante/index.ts',
    'modules/producto_presentacion/index':    'src/modules/producto_presentacion/index.ts',
    'modules/inventario/index':               'src/modules/inventario/index.ts',
    'modules/precio/index':                   'src/modules/precio/index.ts',
    'modules/descuento/index':                'src/modules/descuento/index.ts',
    'modules/promocion/index':                'src/modules/promocion/index.ts',
    'modules/orden_linea/index':              'src/modules/orden_linea/index.ts',
    'modules/orden_pago/index':               'src/modules/orden_pago/index.ts',
    'modules/repartidor/index':               'src/modules/repartidor/index.ts',
    'modules/repartidor_zona/index':          'src/modules/repartidor_zona/index.ts',
    'modules/repartidor_disponibilidad/index':'src/modules/repartidor_disponibilidad/index.ts',
    'modules/saldo_negocio/index':            'src/modules/saldo_negocio/index.ts',
    'modules/tarjeta/index':                  'src/modules/tarjeta/index.ts',
    'modules/metodo_pago/index':              'src/modules/metodo_pago/index.ts',
    'modules/zona/index':                     'src/modules/zona/index.ts',
    'modules/zona_negocio/index':             'src/modules/zona_negocio/index.ts',
    'modules/zona_repartidor/index':          'src/modules/zona_repartidor/index.ts',
    'modules/horario/index':                  'src/modules/horario/index.ts',
    'modules/horario_negocio/index':          'src/modules/horario_negocio/index.ts',
    'modules/configuracion/index':            'src/modules/configuracion/index.ts',
    'modules/configuracion_negocio/index':    'src/modules/configuracion_negocio/index.ts',
    'modules/notificacion_usuario/index':     'src/modules/notificacion_usuario/index.ts',
    'modules/permiso/index':                  'src/modules/permiso/index.ts',
    'modules/rol_permiso/index':              'src/modules/rol_permiso/index.ts',
    'modules/usuario_rol/index':              'src/modules/usuario_rol/index.ts',
    'modules/etiqueta/index':                 'src/modules/etiqueta/index.ts',
    'modules/etiqueta_producto/index':        'src/modules/etiqueta_producto/index.ts',
    'modules/busqueda/index':                 'src/modules/busqueda/index.ts',
    'modules/reporte/index':                  'src/modules/reporte/index.ts',
    'modules/log_actividad/index':            'src/modules/log_actividad/index.ts',
    'modules/plantilla/index':                'src/modules/plantilla/index.ts',
    'modules/plantilla_mensaje/index':        'src/modules/plantilla_mensaje/index.ts',
    'modules/tipo_ubicacion/index':           'src/modules/tipo_ubicacion/index.ts',
    'modules/tipo_movimiento/index':          'src/modules/tipo_movimiento/index.ts',
    'modules/tipo_producto/index':            'src/modules/tipo_producto/index.ts',
    'modules/tipo_descuento/index':           'src/modules/tipo_descuento/index.ts',
    'modules/tipo_promocion/index':           'src/modules/tipo_promocion/index.ts',
    'modules/tipo_reporte/index':             'src/modules/tipo_reporte/index.ts',
  },
  format: ['esm'],
  dts: false,
  splitting: true,
  treeshake: true,
  clean: true,
  sourcemap: true,
  outDir: 'dist',
  external: ['react', 'react-dom'],
});
