import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'react/index': 'src/react/index.ts',
    'modules/sesion/index': 'src/modules/sesion/index.ts',
    'modules/usuario/index': 'src/modules/usuario/index.ts',
    'modules/entrega/index': 'src/modules/entrega/index.ts',
    'modules/negocio/index': 'src/modules/negocio/index.ts',
    'modules/cliente/index': 'src/modules/cliente/index.ts',
    'modules/ubicacion/index': 'src/modules/ubicacion/index.ts',
    'modules/orden/index': 'src/modules/orden/index.ts',
    'modules/producto/index': 'src/modules/producto/index.ts',
    'modules/saldo_usuario/index': 'src/modules/saldo_usuario/index.ts',
    'modules/notificacion/index': 'src/modules/notificacion/index.ts',
    'modules/rol/index': 'src/modules/rol/index.ts',
    'modules/informacion_basica/index': 'src/modules/informacion_basica/index.ts',
    'modules/categoria/index': 'src/modules/categoria/index.ts',
    'modules/link_pago/index': 'src/modules/link_pago/index.ts',
    'modules/concepto/index': 'src/modules/concepto/index.ts',
    'modules/entrega_gps/index': 'src/modules/entrega_gps/index.ts',
    'modules/entrega_evidencia/index': 'src/modules/entrega_evidencia/index.ts',
    'modules/entrega_mensaje/index': 'src/modules/entrega_mensaje/index.ts',
    'modules/entrega_repartidor/index': 'src/modules/entrega_repartidor/index.ts',
    'modules/entrega_usuario_calificacion/index': 'src/modules/entrega_usuario_calificacion/index.ts',
    'modules/entrega_plantilla/index': 'src/modules/entrega_plantilla/index.ts',
    'modules/entrega_multa_aborcion/index': 'src/modules/entrega_multa_aborcion/index.ts',
    'modules/entrega_multa_cancelacion/index': 'src/modules/entrega_multa_cancelacion/index.ts',
    'modules/estatus_entrega/index': 'src/modules/estatus_entrega/index.ts',    'modules/estatus_orden/index':     'src/modules/estatus_orden/index.ts',
    'modules/archivo/index':           'src/modules/archivo/index.ts',    'modules/pago/index': 'src/modules/pago/index.ts',
    'modules/movimiento/index': 'src/modules/movimiento/index.ts',
    'modules/deposito/index': 'src/modules/deposito/index.ts',
    'modules/retiro/index': 'src/modules/retiro/index.ts',
    'modules/abono/index': 'src/modules/abono/index.ts',
    'modules/adeudo/index': 'src/modules/adeudo/index.ts',
    'modules/estatus_pago/index': 'src/modules/estatus_pago/index.ts',
    'modules/tipo_pago/index': 'src/modules/tipo_pago/index.ts',
    'modules/repartidor_on/index': 'src/modules/repartidor_on/index.ts',
    'modules/jornada/index': 'src/modules/jornada/index.ts',
    'modules/uccc/index': 'src/modules/uccc/index.ts',
    'modules/uve/index': 'src/modules/uve/index.ts',
    'modules/uvt/index': 'src/modules/uvt/index.ts',
    // ── Adjuntos ─────────────────────────────────────────────────────────────
    'modules/tipo_adjunto/index':      'src/modules/tipo_adjunto/index.ts',
    'modules/adjunto/index':           'src/modules/adjunto/index.ts',
    'modules/adjunto_referencia/index':'src/modules/adjunto_referencia/index.ts',
    // ── Entregas (extra) ──────────────────────────────────────────────────────
    'modules/entrega_estatus/index':   'src/modules/entrega_estatus/index.ts',
    // ── Notificaciones (extra) ────────────────────────────────────────────────
    'modules/tipo_notificacion/index': 'src/modules/tipo_notificacion/index.ts',
    // ── Aplicaciones & Plataforma ─────────────────────────────────────────────
    'modules/aplicacion/index':               'src/modules/aplicacion/index.ts',
    'modules/plataforma/index':               'src/modules/plataforma/index.ts',
    // ── Usuario Credenciales ──────────────────────────────────────────────────
    'modules/usuario_credenciales/index':     'src/modules/usuario_credenciales/index.ts',
    // ── Contenido ─────────────────────────────────────────────────────────────
    'modules/banner/index':                   'src/modules/banner/index.ts',
    'modules/historia/index':                 'src/modules/historia/index.ts',
    'modules/historia_post/index':            'src/modules/historia_post/index.ts',
    // ── Comercio ──────────────────────────────────────────────────────────────
    'modules/paquete/index':                  'src/modules/paquete/index.ts',
    'modules/seguro/index':                   'src/modules/seguro/index.ts',
    // ── Métodos de Pago Legados ───────────────────────────────────────────────
    'modules/efectivo/index':                 'src/modules/efectivo/index.ts',
    'modules/saldo/index':                    'src/modules/saldo/index.ts',
    'modules/terminal_externa/index':         'src/modules/terminal_externa/index.ts',
    'modules/conekta/index':                  'src/modules/conekta/index.ts',
    'modules/openpay/index':                  'src/modules/openpay/index.ts',
    'modules/pagos_edit_parms/index':         'src/modules/pagos_edit_parms/index.ts',
    // ── Equipos ───────────────────────────────────────────────────────────────
    'modules/equipo/index':                   'src/modules/equipo/index.ts',
    'modules/lider/index':                    'src/modules/lider/index.ts',
    'modules/miembro/index':                  'src/modules/miembro/index.ts',
    'modules/equipo_chat/index':              'src/modules/equipo_chat/index.ts',
    'modules/equipo_chat_usr/index':          'src/modules/equipo_chat_usr/index.ts',
    'modules/equipo_chat_msj/index':          'src/modules/equipo_chat_msj/index.ts',
    // ── Tickets de Soporte ────────────────────────────────────────────────────
    'modules/ticket/index':                   'src/modules/ticket/index.ts',
    'modules/ticket_chat/index':              'src/modules/ticket_chat/index.ts',
    'modules/ticket_chat_msj/index':          'src/modules/ticket_chat_msj/index.ts',
    'modules/ticket_chat_usr/index':          'src/modules/ticket_chat_usr/index.ts',
    // ── Trámites y Flujos de Trabajo ──────────────────────────────────────────
    'modules/tramite/index':                  'src/modules/tramite/index.ts',
    'modules/requisito/index':                'src/modules/requisito/index.ts',
    'modules/validacion/index':               'src/modules/validacion/index.ts',
    'modules/prueba/index':                   'src/modules/prueba/index.ts',
    'modules/solicitud/index':                'src/modules/solicitud/index.ts',
    // ── Notificaciones Extendidas ─────────────────────────────────────────────
    'modules/notificacion_draft/index':       'src/modules/notificacion_draft/index.ts',
    'modules/notificacion_obj/index':         'src/modules/notificacion_obj/index.ts',
  },
  format: ['esm'],
  dts: false,
  splitting: true,
  treeshake: true,
  clean: true,
  sourcemap: true,
  outDir: 'dist',
  external: ['react', 'react-dom'],
});
