import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'react/index': 'src/react/index.ts',
    'modules/sesion/index': 'src/modules/sesion/index.ts',
    'modules/usuario/index': 'src/modules/usuario/index.ts',
    'modules/entrega/index': 'src/modules/entrega/index.ts',
    'modules/negocio/index': 'src/modules/negocio/index.ts',
    'modules/cliente/index': 'src/modules/cliente/index.ts',
    'modules/ubicacion/index': 'src/modules/ubicacion/index.ts',
    'modules/orden/index': 'src/modules/orden/index.ts',
    'modules/producto/index': 'src/modules/producto/index.ts',
    'modules/saldo_usuario/index': 'src/modules/saldo_usuario/index.ts',
    'modules/notificacion/index': 'src/modules/notificacion/index.ts',
    'modules/rol/index': 'src/modules/rol/index.ts',
    'modules/informacion_basica/index': 'src/modules/informacion_basica/index.ts',
    'modules/categoria/index': 'src/modules/categoria/index.ts',
    'modules/negocio_cliente/index': 'src/modules/negocio_cliente/index.ts',
    'modules/link_pago/index': 'src/modules/link_pago/index.ts',
    'modules/concepto/index': 'src/modules/concepto/index.ts',
    'modules/entrega_gps/index': 'src/modules/entrega_gps/index.ts',
    'modules/entrega_evidencia/index': 'src/modules/entrega_evidencia/index.ts',
    'modules/entrega_mensaje/index': 'src/modules/entrega_mensaje/index.ts',
    'modules/entrega_repartidor/index': 'src/modules/entrega_repartidor/index.ts',
    'modules/entrega_usuario_calificacion/index': 'src/modules/entrega_usuario_calificacion/index.ts',
    'modules/entrega_plantilla/index': 'src/modules/entrega_plantilla/index.ts',
    'modules/entrega_multa_aborcion/index': 'src/modules/entrega_multa_aborcion/index.ts',
    'modules/entrega_multa_cancelacion/index': 'src/modules/entrega_multa_cancelacion/index.ts',
    'modules/estatus_entrega/index': 'src/modules/estatus_entrega/index.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: true,
  treeshake: true,
  clean: true,
  sourcemap: true,
  outDir: 'dist',
  external: ['react', 'react-dom'],
});
